### ISSUE TITLE
Question after # 6 are missed labled

### ISSUE THREAD

**Issue by Gonzalomarcylabschool** [The-Marcy-Lab-School/2-0-0-assignment#1]
In the README, there are 2 #6
[Question 6 - add some classes](https://github.com/The-Marcy-Lab-School-Assignments/2-0-0-assignment-Gonzalomarcylabschool#question-6---add-some-classes)

[Question 6 - div for status code info](https://github.com/The-Marcy-Lab-School-Assignments/2-0-0-assignment-Gonzalomarcylabschool#question-6---div-for-status-code-info)

**Comment by MostlyFocusedMike** [comment]
excellent catch, fixed!
