### ISSUE TITLE
Question 5 missing instructions, and bad test.

### ISSUE THREAD

**Issue by Gonzalomarcylabschool** [The-Marcy-Lab-School/2-0-0-assignment#2]
The test won't pass unless the ordered list has a class of hobbies, and it's not in the instructions.
This will prevent a few things from passing.
Also the test says that it need to be an unordered list but then check for a ordered list.

```js
it('has an unordered list of hobbies in main', () => {
    const ol = document.querySelector('main ol#hobbies');
    expect(ol).toBeTruthy();

    scoreCounter.correct(expect); // DO NOT TOUCH
  });
```

**Comment by MostlyFocusedMike** [comment]
ben's pr fixed, and also it says "ordered list" and asks them if it's "ol or ul" which is what I was aiming for
